# Generated by Django 5.2.8 on 2025-11-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="real_name",
            field=models.CharField(blank=True, max_length=20, verbose_name="실명"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=20, verbose_name="닉네임"),
        ),
    ]
